const canvas = document.querySelector("canvas");
canvas.width = 600;
canvas.height = 600;
const hexRadius = 50;
const boardRadius = 3;
const ctx = canvas.getContext("2d");
const players = [new Player("red"), new Player("beige"), new Player("orange")];
let currentPlayer = players[0];
let currentRound = 1;
let diceResult = 0;
const market = new Market();
const progress = new Progress();
const board = new Board(boardRadius, hexRadius);
board.pushNubers();
board.createHexes();
board.drawHexes();
const interface = new Interface(players[0]);
interface.draw();
canvas.addEventListener("click", interface.handleClick);
